name: runoff_app
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  web: ^1.1.1
  flutter_map: ^4.0.0
  latlong2: ^0.8.0
  intl: ^0.20.2

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/geo/danube_shapes.json
    - assets/geo/danube_predictions.csv
    - assets/geo_eval/results_v2/
    - assets/geo_eval/cleaned_graphs_visualizations/
    - assets/geo_eval/train_shapes.json
    
